version: "2.19.1"

services:
  db:
    image: postgres:15.3-alpine
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=bookstore_dev
      - POSTGRES_PASSWORD=bookstore_dev
      - POSTGRES_DB=bookstore_dev_db
    networks:
      - backend_network
  backend:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - . :/usr/src/app/
    ports:
      - "8000:8000"
    env_file:
      - ./env.dev
    networks:
      - backend_network
    depends_on:
      - db

networks:
  backend_network:
    driver: bridge

volumes:
  postgres_data:
